// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: Cmd.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CMD int32

const (
	CMD_CMD_INVALID           CMD = 0
	CMD_CMD_LOGIN_ACCOUNT     CMD = 1001
	CMD_CMD_LOGIN_ACCOUNT_ACK CMD = 1002
)

// Enum value maps for CMD.
var (
	CMD_name = map[int32]string{
		0:    "CMD_INVALID",
		1001: "CMD_LOGIN_ACCOUNT",
		1002: "CMD_LOGIN_ACCOUNT_ACK",
	}
	CMD_value = map[string]int32{
		"CMD_INVALID":           0,
		"CMD_LOGIN_ACCOUNT":     1001,
		"CMD_LOGIN_ACCOUNT_ACK": 1002,
	}
)

func (x CMD) Enum() *CMD {
	p := new(CMD)
	*p = x
	return p
}

func (x CMD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMD) Descriptor() protoreflect.EnumDescriptor {
	return file_Cmd_proto_enumTypes[0].Descriptor()
}

func (CMD) Type() protoreflect.EnumType {
	return &file_Cmd_proto_enumTypes[0]
}

func (x CMD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CMD.Descriptor instead.
func (CMD) EnumDescriptor() ([]byte, []int) {
	return file_Cmd_proto_rawDescGZIP(), []int{0}
}

var File_Cmd_proto protoreflect.FileDescriptor

var file_Cmd_proto_rawDesc = []byte{
	0x0a, 0x09, 0x43, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x2a,
	0x4a, 0x0a, 0x03, 0x43, 0x4d, 0x44, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x11, 0x43, 0x4d, 0x44, 0x5f, 0x4c,
	0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0xe9, 0x07, 0x12,
	0x1a, 0x0a, 0x15, 0x43, 0x4d, 0x44, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x41, 0x43, 0x43,
	0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x41, 0x43, 0x4b, 0x10, 0xea, 0x07, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Cmd_proto_rawDescOnce sync.Once
	file_Cmd_proto_rawDescData = file_Cmd_proto_rawDesc
)

func file_Cmd_proto_rawDescGZIP() []byte {
	file_Cmd_proto_rawDescOnce.Do(func() {
		file_Cmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_Cmd_proto_rawDescData)
	})
	return file_Cmd_proto_rawDescData
}

var file_Cmd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Cmd_proto_goTypes = []interface{}{
	(CMD)(0), // 0: pb.CMD
}
var file_Cmd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Cmd_proto_init() }
func file_Cmd_proto_init() {
	if File_Cmd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Cmd_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Cmd_proto_goTypes,
		DependencyIndexes: file_Cmd_proto_depIdxs,
		EnumInfos:         file_Cmd_proto_enumTypes,
	}.Build()
	File_Cmd_proto = out.File
	file_Cmd_proto_rawDesc = nil
	file_Cmd_proto_goTypes = nil
	file_Cmd_proto_depIdxs = nil
}
