// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: MessageType.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MT int32

const (
	MT_MT_INVALID MT = 0
	MT_GameLogin  MT = 1001
)

// Enum value maps for MT.
var (
	MT_name = map[int32]string{
		0:    "MT_INVALID",
		1001: "GameLogin",
	}
	MT_value = map[string]int32{
		"MT_INVALID": 0,
		"GameLogin":  1001,
	}
)

func (x MT) Enum() *MT {
	p := new(MT)
	*p = x
	return p
}

func (x MT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MT) Descriptor() protoreflect.EnumDescriptor {
	return file_MessageType_proto_enumTypes[0].Descriptor()
}

func (MT) Type() protoreflect.EnumType {
	return &file_MessageType_proto_enumTypes[0]
}

func (x MT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MT.Descriptor instead.
func (MT) EnumDescriptor() ([]byte, []int) {
	return file_MessageType_proto_rawDescGZIP(), []int{0}
}

var File_MessageType_proto protoreflect.FileDescriptor

var file_MessageType_proto_rawDesc = []byte{
	0x0a, 0x11, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x2a, 0x24, 0x0a, 0x02, 0x4d, 0x54, 0x12, 0x0e, 0x0a,
	0x0a, 0x4d, 0x54, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a,
	0x09, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0xe9, 0x07, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MessageType_proto_rawDescOnce sync.Once
	file_MessageType_proto_rawDescData = file_MessageType_proto_rawDesc
)

func file_MessageType_proto_rawDescGZIP() []byte {
	file_MessageType_proto_rawDescOnce.Do(func() {
		file_MessageType_proto_rawDescData = protoimpl.X.CompressGZIP(file_MessageType_proto_rawDescData)
	})
	return file_MessageType_proto_rawDescData
}

var file_MessageType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_MessageType_proto_goTypes = []interface{}{
	(MT)(0), // 0: pb.MT
}
var file_MessageType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_MessageType_proto_init() }
func file_MessageType_proto_init() {
	if File_MessageType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MessageType_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MessageType_proto_goTypes,
		DependencyIndexes: file_MessageType_proto_depIdxs,
		EnumInfos:         file_MessageType_proto_enumTypes,
	}.Build()
	File_MessageType_proto = out.File
	file_MessageType_proto_rawDesc = nil
	file_MessageType_proto_goTypes = nil
	file_MessageType_proto_depIdxs = nil
}
